coverage:
  precision: 2
  round: nearest
  range: 99..100
  status:
    project:
      default:
        target: 98%    # the required coverage value
        threshold: 3%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        target: 100%
        threshold: 1%
        informational: true
codecov:
  require_ci_to_pass: false